# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('book_name', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('arts', 'Arts & Photography'), ('biographies', 'Biographies & Memoirs'), ('children', "Children's Books"), ('histosy', 'History'), ('literature', 'Literature & Fiction'), ('mystery', 'Mystery & Suspense'), ('romance', 'Romance'), ('sci-fi', 'Sci-Fi & Fiction'), ('teens', 'Teens & Young Adult'), ('textbook', 'Textbooks'), ('other', 'Other')], default=('other', 'Other'), max_length=20)),
                ('book_cover', models.ImageField(default='media/books/book_cover/no_cover.jpg', upload_to='media/books/book_cover')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
